name: "Post to Bluesky"

on:
  workflow_dispatch:
  schedule:
    - cron: "7 * * * *"
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - run: npm ci
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      - name: Setup dependencies
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Run my R script
        run: |
              Rscript src/text_generator.R  # adjust path to your script
      - run: npm run build
      - name: Configure git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
      - name: Send post
        run: npm start
        env:
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
      #- name: Commit and push changes
      #  run: |
      #    git add .
      #    git commit -m "Automated commit from GitHub Actions"
      #    git push origin main
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
